version: '3.6'
services:
  server:
    image: server:init
    build:
      context: .
      dockerfile: Dockerfile
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:8080